version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.13.0
  win: circleci/windows@2.4.1

executors:
  win/default:
      shell: bash.exe
jobs:
  build-and-push:
    executor: 
      name: win/default
      shell: bash.exe
    steps:
      - checkout
      - gcp-gcr/build-image:
          image: gcp-windowsorb-test
          no_output_timeout: 20m
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  build_job:
    jobs:
      - gcp-gcr/build-and-push-image:
          context: GCP
          executor: gcp-gcr/default
          image: gcp-orb-test
      - gcp-gcr/build-and-push-image:
          context: GCP
          docker-context: /Windows
          executor: win/default
          image: gcp-windowsorb-test
      
