version: 2.1

jobs:
  check_git_branch_triggers:
    docker:
      - image: cimg/base:lts
    resource_class: small
    steps:
      - checkout
      - run:
          name: Determine git branches
          command: |
            git branch -r >> BranchList.txt
            cat BranchList.txt



workflows:
  build_job:
    jobs:
      - check_git_branch_triggers
      