version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.14.1
  win: circleci/windows@2.4.1

executors:
  my-latest-ubuntu:
    machine:
     image: ubuntu-2004:202010-01
jobs:
  build-and-push:
    executor: 
      name: my-latest-ubuntu
      #shell: bash.exe
    steps:
      - checkout
      - run: pwd
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: gcp-orb-windowstest
          dockerfile: WindowsDockerfile
      - gcp-gcr/push-image:
          image: gcp-orb-windowstest
workflows:
  build_job:
    jobs:
      - gcp-gcr/build-and-push-image:
          context: GCP
          executor: my-latest-ubuntu
          image: gcp-orb-test
      - build-and-push:
          context: GCP
      
