version: 2.1

jobs:
  check_git_branch_triggers:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: Determine git branches
          command: |
            git ls-remote --heads origin | awk '{print $2}' | sed 's/refs\/heads\///g' | grep -F 'patch' > BranchList.txt
            curl --request GET \
              --header "Circle-Token: $CIRCLE_TOKEN" \
              --header "Accept: application/json"   \
              --url 'https://circleci.com/api/v2/project/gh/klsember/test-gcp-orbs/schedule' > schedulelist.json
            export result=$(jq '.items[]' schedulelist.json)
            echo $result
            export BRANCH='klsember-patch-1'
            export scheduledata=$( jq --arg branch "$BRANCH" \
              '{"name": $branch, "timetable": {"per-hour": 1, "hours-of-day": [1], "days-of-week": ["TUE"]}, "attribution-actor": "system", "parameters": {"branch": $branch}, "description": "string"}' )
            curl --request POST \
              --url https://circleci.com/api/v2/project/gh/klsember/test-gcp-orbs/schedule \
              --header "Circle-Token: $CIRCLE_TOKEN" \
              --header 'content-type: application/json' \
              --data "$scheduledata"



workflows:
  build_job:
    jobs:
      - check_git_branch_triggers:
          context:
            - api_context
      