version: 2.1

jobs:
  check_git_branch_triggers:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: Determine git branches
          command: |
            git ls-remote --heads origin | awk '{print $2}' | sed 's/refs\/heads\///g' >> BranchList.txt
            cat BranchList.txt



workflows:
  build_job:
    jobs:
      - check_git_branch_triggers
      