version: 2.1

jobs:
  check_git_branch_triggers:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: Determine git branches
          command: |
            git ls-remote --heads origin | awk '{print $2}' | sed 's/refs\/heads\///g' >> BranchList.txt
            curl --request GET \
              --url 'https://circleci.com/api/v2/project/gh/klsember/test-gcp-orbs/schedule' \
              --header 'authorization: Circle-Token $CIRCLE_TOKEN'



workflows:
  build_job:
    jobs:
      - check_git_branch_triggers
      